# Generated by Django 3.0.7 on 2020-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zper_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.DurationField(),
        ),
    ]
