# Generated by Django 3.0.7 on 2020-07-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zper_api', '0004_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=260)),
                ('processed', models.BooleanField(default=False)),
                ('memo', models.CharField(max_length=260, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zper_api.Product')),
            ],
        ),
    ]
