# Generated by Django 3.0.7 on 2020-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zper_api', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyId', models.CharField(max_length=64)),
                ('pubkey', models.CharField(max_length=900)),
                ('expirary', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='memo',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
